/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'hf' at '4/19/15 11:56 PM' with Gradle 2.2.1
 *
 * @author hf, @date 4/19/15 11:56 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
