
var TREE_ITEMS = [
 ['LG', '',
   ['Admin','',
    ['Jogo','',
     ['Aprova Roteiro', '/admin.solicitacaoRoteiroJogo.action'],
     ['Aprova Texto', '/admin.solicitacaoTextoJogo.action'],
    ],
    ['Emulador','',
     ['Aprova Roteiro', '/admin.solicitacaoRoteiroEmulador.action'],
     ['Aprova Texto', '/admin.solicitacaoTextoEmulador.action'],
    ],
   ],
   ['Site', '',
    ['Artigos', 'artigo.action'],
    ['Artigos Externos', 'artigoExterno.action'],
    ['Novidades', 'novidade.action'],
   ],
   ['Emuladores', '',
    ['Emuladores', 'emulador.action'],
    ['Roteiro de instala&ccedil;&atilde;o', 'roteiroInstalacaoEmu.action'],
    ['Bibliotecas usadas', 'bibliotecaXemulador.action'],
    ['Telas', 'telaDeEmulador.action'],
    ['Vers&otilde;es', 'versaoDeEmulador.action'],
    ['Textos', 'textoDeEmulador.action'],
    ['Reviews','reviewDeEmulador.action'],
   ],
   ['Jogos', '',
    ['Jogos', 'jogo.action'],
    ['Textos reprovados', '/admin.solicitacaoTextoJogo.action'],
    ['Roteiro de instala&ccedil;&atilde;o', 'roteiroInstalacaoJogo.action'],
    ['Roteiro reprovados', '/admin.solicitacaoRoteiroJogo.action'],
    ['Bibliotecas usadas', 'bibliotecaXjogo.action'],
    ['Telas', 'telaDeJogo.action'],
    ['Upload de imagem', 'jogoImagem.jsp'],
    ['Vers&otilde;es', 'versaoDeJogo.action'],
    ['Textos', 'textoDeJogo.action'],
    ['Reviews', 'reviewDeJogo.action'],
   ],
  ],
];

