
var TREE_ITEMS = [
 ['LG', '',
   ['Admin','',
    ['Jogo','',
     ['Aprova Roteiro', '/games/admin-solicitacaoRoteiroJogo'],
     ['Aprova Texto', '/games/admin-solicitacaoTextoJogo'],
     ['Aprova Update', '/games/admin-solicitacaoAlteracaoJogo'],
     ['Aprova Novo', '/games/admin-solicitacaoNovoJogo'],
    ],
    ['Emulador','',
     ['Aprova Roteiro', '/games/admin-solicitacaoRoteiroEmulador'],
     ['Aprova Texto', '/games/admin-solicitacaoTextoEmulador'],
    ],
    ['Novidade', '/games/admin-solicitacaoNovidade'],
    ['Actions','/games/stats']
   ],
   ['Site', '',
    ['Novidades', '/games/novidade'],
    ['Novidades agendadas', '/games/novidadeagendada'],
    ['Jogos favoritos', '/games/jogosFavoritos'],
    ['Emuladores favoritos', '/games/emuladoresFavoritos'],
    ['Banner', '/games/banner'],
    ['Artigos Externos', '/games/artigoExterno'],
    ['Info do Dia', '/games/infoDoDia'],
    ['Controle de Cache', '/games/cache'],
    ['Enquetes', '/games/enqueteCRUD'],
    ['Enquetes x votos', '/games/votoXenquete'],
    ['Jogos x votos', '/games/votoXjogo'],
    ['Emuladores x votos', '/games/votoXemulador'],
    ['Site Log', '/games/sitelog'],
    ['Update Logs', '/games/updatelog'],
   ],
   ['Bibliotecas', '',
    ['Bibliotecas', '/games/biblioteca'],
    ['Roteiro de instala&ccedil;&atilde;o', '/games/roteiroInstalacaoBiblioteca'],
    ['Vers&otilde;es', '/games/versaoDeBiblioteca'],
   ],
   ['Emuladores', '',
    ['Emuladores', '/games/emulador'],
    ['Roteiro de instala&ccedil;&atilde;o', '/games/roteiroInstalacaoEmu'],
    ['Bibliotecas usadas', '/games/bibliotecaXemulador'],
    ['Telas', '/games/telaDeEmulador'],
    ['Vers&otilde;es', '/games/versaoDeEmulador'],
    ['Textos', '/games/textoDeEmulador'],
    ['Reviews','/games/reviewDeEmulador'],
   ],
   ['Jogos', '',
    ['Jogos', '/games/jogo'],
    ['Jogos EN', '/games/jogoEN'],
    ['Textos reprovados', '/games/admin-solicitacaoTextoJogo'],
    ['Roteiro de instala&ccedil;&atilde;o', '/games/roteiroInstalacaoJogo'],
    ['Roteiro reprovados', '/games/admin-solicitacaoRoteiroJogo'],
    ['Bibliotecas usadas', '/games/bibliotecaXjogo'],
    ['Telas', '/games/telaDeJogo'],
    ['Vers&otilde;es', '/games/versaoDeJogo'],
    ['Textos', '/games/textoDeJogo'],
    ['Reviews', '/games/reviewDeJogo'],
   ],
   ['Distros', '',
    ['Fabricantes', '/games/fabricante'],
    ['Distros', '/games/distro'],
    ['Vers&atilde;o', '/games/versaoDeDistro'],
   ],
   ['Usu&aacute;rios', '',
    ['Usu&aacute;rios', '/games/usuario'],
    ['Colaboradores', '/games/colaborador'],
    ['Artigos', '/games/artigo'],
    ['Textos de Jogo', '/games/textoDeJogo'],
    ['Textos de Emulador', '/games/textoDeEmulador'],
   ],
  ],
 ['TOE', '',
   ['Tabela de Equivalentes', '',
    ['Licen&ccedil;as', '/games/licenca'],
    ['Grupos', '/games/grupo'],
    ['Subgrupos', '/games/subgrupo'],
    ['Aplica&ccedil;&otilde;es Windows', '/games/aplicacaoWin'],
    ['Aplica&ccedil;&otilde;es Linux', '/games/aplicacaoLin'],
    ['Aplica&ccedil;&otilde;es Windows e Linux', '/games/aplicacaoWinELin'],
    ['Notas das aplica&ccedil;&otilde;es', '/games/nota'],
   ],
  ],
];

