/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'hf' at '4/19/15 11:56 PM' with Gradle 2.2.1
 *
 * @author hf, @date 4/19/15 11:56 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
